name: Codacy Coverage Reporter

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  report-coverage:
    if: github.repository == 'everoddandeven/monero-python'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          github-token: ${{ secrets.API_GITHUB }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Report python coverage
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          language: python
          coverage-reports: coverage.xml

      - name: Report c coverage
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          language: c
          coverage-reports: coverage.info

      - name: Report c++ coverage
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          language: cpp
          coverage-reports: coverage.info
